### ISSUE TITLE
18.04: 20.04 notifications are dismissed by default

### ISSUE THREAD

**Issue by leviport** [pop-os/upgrade#103]
![dismissed](https://user-images.githubusercontent.com/13512097/80749651-fde3de80-8ae3-11ea-8d27-acd72c9bc0d3.png)

**Comment by jacobgkau** [comment]
After installing 18.04, notifications are dismissed by default due to the installation timestamp being greater than the release date of 20.04, which is correct behavior; after removing the `dismissed` file, notifications do work as expected.
