### ISSUE TITLE
Firmware upgrade from gnome-control-center

### ISSUE THREAD

**Issue by brs17** [pop-os/upgrade#11]

**Comment by brs17** [comment]
Gnome-control-center crashed when I selected the `Reboot&Upgrade` button.

**Comment by mmstick** [comment]
I may know the cause. Building GCC locally and running it through Valgrind can tell you exactly what did it.

**Comment by mmstick** [comment]
Latest commit may fix it.

**Comment by brs17** [comment]
No luck thus far, information put https://github.com/pop-os/gnome-control-center/pull/12
