### ISSUE TITLE
Upgrader Does Not State That It Will Remove Sources During Confirmation

### ISSUE THREAD

**Issue by TechnologyMan101** [pop-os/upgrade#120]
Although removing sources is intentional, it does not tell me this anywhere before pressing the Reboot and Upgrade button. This might potentially make people think that the upgrade was unsuccessful and broke some stuff.

I'm also still concerned about how upgrading will delete **default** Pop!_OS source code repos.

**Comment by TechnologyMan101** [comment]
Noticed that this isn't happening anymore when upgrading to 20.10, so I will be closing this issue.

**Comment by jacobgkau** [comment]
Sources are still "reset to default" during a release upgrade, but old sources are now disabled (commented out) rather than being removed entirely, which allows them to be re-enabled via the Repoman GUI.
