### ISSUE TITLE
Release upgrade status: release upgrade aborted: failed to apply system repair before upgrade: error checking and fixing fstab pop-upgrade: dbus client error: calling ReleaseUpgradeFinalize method failed

### ISSUE THREAD

**Issue by hsantos92** [pop-os/upgrade#130]
Distribution (run cat /etc/os-release):

VERSION="20.04 LTS"

Issue/Bug Description:

I get the following error when upgrading from 20.04 to 20.10 in the terminal

$ pop-upgrade release upgrade
Current Release: 20.04
Upgrading to: 20.10
New version available: 1
Release upgrade status: release upgrade aborted: failed to apply system repair before upgrade: error checking and fixing fstab
pop-upgrade: dbus client error: calling ReleaseUpgradeFinalize method failed

If I try to update in the settings menu, I get the error below.
![Screenshot from 2020-10-24 15-10-50](https://user-images.githubusercontent.com/55033813/97095210-751caa00-1611-11eb-9fa2-f3b3aaaf66ae.png)

**Comment by vishnugopal** [comment]
Can you paste in your /etc/fstab?

I had the same problem, and this was because I had a non `UUID=` starting line in /etc/fstab, fixed it by converting it to the blkid format as suggested in the comments:

Before:

```
/dev/disk/by-uuid/6df0c207-257b-4e56-bd6e-3f32ea0437b1 /mnt/media auto nosuid,nodev,nofail,x-gvfs-show 0 0
```

After:

```
UUID=6df0c207-257b-4e56-bd6e-3f32ea0437b1 /mnt/media auto nosuid,nodev,nofail,x-gvfs-show 0 0
```

**Comment by hsantos92** [comment]
I did something sort of similar to the fstab, I added # anything that had /dev/disk (backup, games drive, etc) in front and only left my root, swap, etc. I did had some other minor issues, so far eveything seems to be ok. 

See more details [here](https://github.com/pop-os/pop/issues/1324
)
