### ISSUE TITLE
"pop-upgrade recovery default-boot" panics

### ISSUE THREAD

**Issue by j-tai** [pop-os/upgrade#141]
This command causes a panic:

```
$ RUST_BACKTRACE=1 pop-upgrade recovery default-boot
checking if pop-upgrade requires an update
thread 'main' panicked at 'internal error: entered unreachable code', src/cli/mod.rs:73:18
stack backtrace:
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: <unknown>
  12: <unknown>
  13: <unknown>
  14: __libc_start_main
  15: <unknown>
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by bflanagin** [comment]
Confirmed in Pop!_OS 20.10 
 
pop-upgrade:
  Installed: 0.1.1~1608137131~20.10~d3bfb98
  Candidate: 0.1.1~1608137131~20.10~d3bfb98
  Version table:
 *** 0.1.1~1608137131~20.10~d3bfb98 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu groovy/main amd64 Packages
        100 /var/lib/dpkg/status

**Comment by danieleades** [comment]
Looking at the code, while the command exists, it's not actually implemented.

**Comment by j-tai** [comment]
Looks like this is fixed.
