### ISSUE TITLE
Perform upgrade with recovery partition

### ISSUE THREAD

**Issue by brs17** [pop-os/upgrade#15]

**Comment by brs17** [comment]
@mmstick After I typed in the decrypt password, I hit enter (saw nothing happen), pressed enter a few more times, and then the screen transitioned a few times before telling me the upgrade failed.

Journald logs attached: 
[failed_install.log](https://github.com/pop-os/upgrade/files/3082632/failed_install.log)

**Comment by brs17** [comment]
I also notice that the options I am given upon failure are: `Try Recovery Shell`, and `Refresh OS`. The `Try Recovery Shell` option does not seem to do anything.

**Comment by mmstick** [comment]
Yeah, the recovery shell hasn't been implemented yet, nor has the Refresh OS button.

**Comment by brs17** [comment]
Closing this as there has been a lot of work done on `pop-upgrade` and this will need to be completely retested at a later point in time.
