### ISSUE TITLE
If repos are not compatible in a release upgrade, tell the client which repos are broken

### ISSUE THREAD

**Issue by mmstick** [pop-os/upgrade#16]
This requires:

- [x] https://github.com/pop-os/apt-fetcher/issues/5 must be implemented (WIP)
- [x] Add a new dbus signal to alarm the client that some changes to the repository configuration are necessary.
- [x] Add a new dbus method to allow the client to make required changes, which will either be:
  - Keep the repo(s) at their current release
  - Disable the repo(s)
- [x] Changes to the CLI client to the listen to this signal, display information to the user, and use that method
- [x] A means to disable repo release upgrades for repos that have been selected to not be upgraded

**Comment by brs17** [comment]
I had added https://github.com/pop-os/session/pull/7 which should be a ppa that only exists in cosmic and not disco. I was never prompted about this ppa being disabled and when I finished the upgrade, sources were not updated. Checking repoman, most of the settings were still unchecked and there were some Ubuntu repos I'd never seen before:

![repoman](https://user-images.githubusercontent.com/7460774/56901667-e8ae1d00-6a55-11e9-8555-f4321408dc0a.png)

**Comment by mmstick** [comment]
Do you have logs from `journalctl -u pop-upgrade`?

**Comment by mmstick** [comment]
This is what I get with the firmware remote:

![Screenshot from 2019-04-29 09-57-47](https://user-images.githubusercontent.com/4143535/56909326-4a29b800-6a65-11e9-85c6-1bf810395383.png)

**Comment by brs17** [comment]
I do not have the system in that state anymore, I will (attempt) to recreate the issue again.

**Comment by brs17** [comment]
I now see the error as well by adding `staging/firmware`.

**Comment by brs17** [comment]
@mmstick testing upgrade from 18.04->19.04 via gnome-control-center, I am prompted twice(for the same repository) with the "Unsupported repository" pop-up. I was not selecting the checkbox. 

Logs:
[journal.log](https://github.com/pop-os/gnome-control-center/files/3135322/journal.log)

**Comment by mmstick** [comment]
The logs detail that it never received the `RepoModify` signal. Client say anything?

**Comment by brs17** [comment]
All I did was press `Accept`. Next time I'm going through the upgrade, I'll show you.

**Comment by mmstick** [comment]
Running GCC from a terminal with `env G_MESSAGES_DEBUG=all gnome-control-center` will give useful logs for client-side interactions.

**Comment by mmstick** [comment]
If building from source, running it through `valgrind` is also useful for detecting memory leaks / bad allocations and frees.

**Comment by brs17** [comment]
> I had added [pop-os/session#7](https://github.com/pop-os/session/pull/7) which should be a ppa that only exists in cosmic and not disco. I was never prompted about this ppa being disabled and when I finished the upgrade, sources were not updated. Checking repoman, most of the settings were still unchecked and there were some Ubuntu repos I'd never seen before:
> 
> ![repoman](https://user-images.githubusercontent.com/7460774/56901667-e8ae1d00-6a55-11e9-8555-f4321408dc0a.png)

This still seems to be an issue after the upgrade I just did (through the recovery partition)

**Comment by brs17** [comment]
Going to close this as discussion has moved to https://github.com/pop-os/upgrade/pull/34
