### ISSUE TITLE
Pop!_OS PPA not rolled back after canceling upgrade

### ISSUE THREAD

**Issue by jacobgkau** [pop-os/upgrade#193]
**Steps to recreate:**
1. On a Groovy system, download the upgrade.
2. After downloading has completed, click Upgrade.
3. In the changelog dialog, click Cancel.
4. After `Canceling upgrade` has gone away, `system76-ubuntu-pop-groovy.list` and `pop-os-ppa.list` are both present and have active lines. The first list contains a `groovy` entry and the second list contains a `hirsute` entry.
5. Run `sudo apt update` and observe that Hirsute packages are available for installation.

**Expected behavior:**
This is a little messy because the installer on the ISO and pop-upgrade use two different default filenames for this file. Some scenarios that might work:
- `pop-os-ppa.list` could be removed if `system76-ubuntu-pop-x.list` is restored.
- `pop-os-ppa.list` could be edited to the current distribution version when canceling an upgrade (which would at least prevent further issues), and `system76-ubuntu-pop-x.list` could then optionally be left out from the backup/restore.

**Comment by jacobgkau** [comment]
This is still affecting cancelled and rolled-back upgrades from 21.04 to 21.10.

**Comment by mmstick** [comment]
I think we can remove all non-`.save` files when restoring. There's no `.save` file for the new source list, so it'd be gone on a restore of former source files.
