### ISSUE TITLE
How to update

### ISSUE THREAD

**Issue by bodhi-baum** [pop-os/upgrade#198]
I got an older laptop with pop os from 2019. Now I would like to update it to the newest version, without having to burn an iso, 
The sources from the 2019 version are outdated. How can I get access to up-to-date sources?

**Comment by jacobgkau** [comment]
Thank you for using Pop!_OS. This is not a forum, this is a development bug tracker. System76 customers can contact support at [support.system76.com](https://support.system76.com/). Users of third-party hardware can seek community support on the [Mattermost chat room](https://chat.pop-os.org/) or the [subreddit](https://reddit.com/r/pop_os/).

There are instructions to upgrade from older releases in the "Upgrade Pop!_OS" support article here: https://support.system76.com/articles/upgrade-pop#upgrading-older-releases
