### ISSUE TITLE
Upgrade restore partition before dist-upgrade

### ISSUE THREAD

**Issue by WatchMkr** [pop-os/upgrade#215]
With an updated restore partition, the user can use it to refresh their installation to the new version if the upgrade fails.

**Comment by jacobgkau** [comment]
This was implemented by https://github.com/pop-os/upgrade/pull/211/commits/0ea0f4de54e417bc47266a2b22e27ae0dc800d43 in https://github.com/pop-os/upgrade/pull/211.
