### ISSUE TITLE
Looses boot parameters on upgrade + RFC

### ISSUE THREAD

**Issue by gjrtimmer** [pop-os/upgrade#216]
[Original Full Discussion can be found here](https://github.com/pop-os/kernelstub/issues/53)

I've recently upgraded from `20.10` to `21.04`. I'm running Pop!_OS on a Clevo barebone. I had some very nice boot parameters set in my `kernelstub.conf`. They were all wiped. Unfortunately I did not have a backup of it.

I understand the decision to have the boot parameters wiped by the upgrader to ensure the successful boot, however this can also be considered problematic.

Possible problems with the current implementation:
* boot parameters are removed which are required for successful boot (GPU params ?!?)
* boot parameters are removed which contain a user config

# RFC to upgrader
* upgrader should copy current kernel config to `/etc/kernelstub/configuration-<RELEASE>`; when upgrading from `20.10` to `21.04` kernelstub config should be retained as `/etc/kernelstub/configuration-20.10` or it should be moved into a directory like `previous`. PLEASE ENSURE RELEASE VERSION NUMBER IN FILE, we do not want to override this on each upgrade.
* upgrader should provide migration wizard for boot params when preforming the upgrade
  * DEFAULT == clear boot params to retain backwards compatibility with current workflow
  * Provide options to copy over ALL params
  * Provide options to copy over selectively.

Reason for last option, very important that it is included because there is a lot of hardware out there, that require some boot option to ensure your screen works or to boot successful, and the upgrade wizard should be able to handle this.

Please comment on my proposal.

**Comment by mmstick** [comment]
As far as I know, pop-upgrade doesn't touch the kernelstub files at all, so they should remain the same as before.

**Comment by gjrtimmer** [comment]
@mmstick can we verify this somehow ?

**Comment by gjrtimmer** [comment]
Then I have to look why my parameters where missing on my system.

Thank you all for your time.
