### ISSUE TITLE
Add scheduling and auto-update options 

### ISSUE THREAD

**Issue by WatchMkr** [pop-os/upgrade#217]
Daily operating system updates can be distracting. Let's remove the distraction with notification, scheduling and automatic update options.

Options located in Settings > OS Upgrades

Settings:
Show available updates - Daily | Weekly | Monthly

Automatic updates
Automatically install - Security updates | All updates 
Schedule automatic updates (toggle on with day of week and time)

**Comment by maria-komarova** [comment]
The mockup for the options includes:
- Toggle for Automatic updates
- The ability to customize the settings - security updates vs all updates, scheduling option. The settings are in the dialog. 
- Notifications could be set to appear daily, weekly, or monthly. When automatic updates are set to "all updates", users shouldn't actually get any notifications for available updates. Caption inside the listbox for notifications setting aims to specify that. 

## Default View:
![OS Upgarde Default](https://user-images.githubusercontent.com/57502897/138168404-e4fafbbe-88d9-4f97-b2e2-1830a2f8001d.png)

## When Automatic Updates are On
- Automatically Install - Security Updates
- Time - When Available

![OS Upgrade - Automatic On Default](https://user-images.githubusercontent.com/57502897/138168902-8a5363d8-6174-4381-9476-dbb88d6519b7.png)

### Same state but assuming someone already scheduled the time (just the copy change next to "Automatically Install")

![OS Upgrade - Automatic On - custom schedule](https://user-images.githubusercontent.com/57502897/138169078-0052a1ba-c489-42ae-8477-89a37e38e8a9.png)

## Dialog for customizing automatic updates
![OS Upgrade Automatic On - Dialog with Settings](https://user-images.githubusercontent.com/57502897/138169219-9847bdcd-1391-449a-86f5-6d2f6c571bd7.png)
![OS Upgrade Automatic On - Dialog with Settings-Dropdown options](https://user-images.githubusercontent.com/57502897/138169278-2b121f42-3f7d-46ef-991c-b4ac826ba7cc.png)
![OS Upgrade Automatic On - Dialog with Settings - Schedule](https://user-images.githubusercontent.com/57502897/138169289-235b9e1f-7d3d-405b-bf16-27e62e7bdcdf.png)


Link to the clickable mockups: https://www.figma.com/proto/UAyDdqkbOMO3b7XK43jp3s/Settings?node-id=103%3A848&scaling=min-zoom&page-id=0%3A1&starting-point-node-id=103%3A848
Link to the mockups page in Figma: https://www.figma.com/file/UAyDdqkbOMO3b7XK43jp3s/Settings?node-id=103%3A790

**Comment by maria-komarova** [comment]
Speaking of notifications, do we need some kind of notification for when the updates are happening automatically informing users about how many updates were installed? Maybe those could be after the scheduled time?

**Comment by maria-komarova** [comment]
We currently send the user to the Pop Shop, right? So I thought the notifications for available updates could be doing the same. 
To clarify just in case, my question was about notifications for the updates that have been installed automatically so that would be just the information notification, no action required from the user. If we think it would be helpful for people to get this information of course.

**Comment by maria-komarova** [comment]
Yes, but we don't need available updates notifications for automatic updates, only for the ones that are not.

**Comment by mmstick** [comment]
But I can definitely patch Pop Shop to use the same service

**Comment by maria-komarova** [comment]
Hm.. Do you mean that in order to have any updates be automatic it might be better to move them out of Pop Shop?

**Comment by maria-komarova** [comment]
Does that mean that all updates need to be exposed outside of Pop Shop now, even manual updates? Just trying to make sure before iterating on that.

**Comment by mmstick** [comment]
I can integrate the service into Pop Shop so that there's no need to have a dedicated area outside of it somewhere.

**Comment by maria-komarova** [comment]
Sounds great, thanks. I think it would be best for consistency.
