### ISSUE TITLE
Design recovery partition upgrade screens

### ISSUE THREAD

**Issue by brs17** [pop-os/upgrade#22]
The following is what the recovery partition upgrades screens currently look like. Questions/Concerns I have:
- Is that the right image we want to include for upgrading? Should this be any different than the image used during installation?
- Title bar says "Install Pop!_OS 19.04", would we not want it to say "Upgrade to Pop!_OS 19.04" instead?

![Screenshot from 2019-04-26 17-04-42](https://user-images.githubusercontent.com/7460774/56832523-7a851280-6829-11e9-8218-7bbc5e18843e.png)

![Screenshot from 2019-04-26 17-06-08](https://user-images.githubusercontent.com/7460774/56832522-7a851280-6829-11e9-8b71-db93ff89c54a.png)

![Screenshot from 2019-04-26 17-16-36](https://user-images.githubusercontent.com/7460774/56832521-7a851280-6829-11e9-97f3-ea343b50816a.png)

Any other thoughts?

**Comment by WatchMkr** [comment]
@brs17 I think the current image is a good representation for Decrypt OS. Upgrade should be the installation progress screen as you suggested.

I agree with changing the header title to Upgrade to....

For copy check with Alex. I think it could be a bit more personal. Also “Attempting” doesn’t instill a lot of confidence. Let’s come up with a different verb there.

**Comment by mmstick** [comment]
Current labels in the installer are:

- `Upgrading to ${version}` when  in upgrade mode
- `Refresh OS` when in refresh mode
- `Upgrading installation to the new release` on an upgrade attempt
- `Problems found during upgrade -- repairing them` on a failed upgrade and automatic repairs are being performed
- `Resuming upgrade of installation to the new release` after successfully correcting errors and resuming the upgrade

**Comment by brs17** [comment]
Current plan is to continue with the systemd upgrade process and add additional functionality to the recovery partition as needed.
