### ISSUE TITLE
Failed to upgrade from 21.04 to 21.10 "failure to simulate upgrade"

### ISSUE THREAD

**Issue by BobbyByrne** [pop-os/upgrade#220]
Loaded up a VM to test out the pre-release. I installed using the latest 21.04 installation iso, and then used the command

`sudo apt update && sudo apt upgrade -y && sudo pop-upgrade release upgrade -f`

Process exits during the simulate upgrade phase with the following output:

> Release upgrade status: release upgrade aborted: failure to simulate upgrade
> pop-upgrade: calling ReleaseUpgradeFinalize method failed
>   caused by: release upgrade cannot be finalized, because a release upgrade was not performed

attached is my journalctl output for pop-upgrade. It looks like the error is from the apt command trying to remove pop-desktop

> ...
> WARNING: The following essential packages will be removed.
> This should NOT be done unless you know exactly what you are doing!
>   pop-desktop pop-session (due to pop-desktop)
>   pop-default-settings (due to pop-desktop)
> 870 upgraded, 40 newly installed, 7 to remove and 0 not upgraded.
> E: Essential packages were removed and -y was used without --allow-remove-essential.
> [ERROR] pop_upgrade src/release/mod.rs:616: failed to fetch packages: failure to simulate upgrade: status is unknown: exit code: 100
> ...
 
[journalctl_output_pop-upgrade_21.04_to_21.10.txt](https://github.com/pop-os/upgrade/files/7275048/journalctl_output_pop-upgrade_21.04_to_21.10.txt)

**Comment by mmstick** [comment]
Not supported yet. Requires using the impish branch.

**Comment by jacobgkau** [comment]
This issue was reported before https://github.com/pop-os/upgrade/pull/223 was merged. https://github.com/pop-os/upgrade/pull/223 added support for upgrading to 21.10. I'm closing this issue to keep the issue list relevant for current issues. Thank you for the report.
