### ISSUE TITLE
Upgrade from 21.04 to 21.10 failed

### ISSUE THREAD

**Issue by horrokotoj** [pop-os/upgrade#236]
Hi,
I just tried upgrading from 21.04 to 21.10 but the upgrade seem to have failed.
After a reboot I'm getting this message.
![image](https://user-images.githubusercontent.com/53189151/146438722-52b33382-cd39-47a4-b46e-a26663914463.png)

When running ´sudo dpkg --configure -a´ I get the following:

![image](https://user-images.githubusercontent.com/53189151/146446715-70b15153-a787-4c82-b280-65c9ad510434.png)

What might have caused this?

**Comment by horrokotoj** [comment]
When I shutdown I also get this:

![image](https://user-images.githubusercontent.com/53189151/146446989-b507413c-1e8a-4280-a4ed-50c969d29824.jpeg)

**Comment by jacobgkau** [comment]
Did you previously attempt to upgrade, have a failed upgrade, or cancel an upgrade before you saw what's in the first screenshot?

A user in our Mattermost chat room ran into a similar issue with the `ppp` package and we found a solution: https://chat.pop-os.org/pop-os/pl/gcntgbbdopd47ehfx5wfmqmh9c 

The fix boiled down to these commands, assuming your situation is exactly the same as that one:
```
mkdir packages
cd packages
apt download gnome-control-center=1:40.0-1ubuntu5pop0~1637613403~21.10~2dafb76 network-manager=1.32.12-0ubuntu1 gnome-control-center-data=1:40.0-1ubuntu5pop0~1637613403~21.10~2dafb76 network-manager-pptp=1.2.8-3build1 network-manager-pptp-gnome=1.2.8-3build1 php-pear=1:1.10.12+submodules+notgz+20210212-1ubuntu1 php-xml=2:8.0+82~0build1 php8.0-xml=8.0.8-1ubuntu0.1
sudo dpkg --force-all -i ./*.deb
sudo apt install -f
cd ..
rm -r ./packages
sudo apt update
sudo apt full-upgrade
sudo apt autoremove --purge
sudo apt install pop-desktop
sudo systemctl reboot
```

The second photo is showing a kernel panic, which is hardware-specific and not likely to be related to pop-upgrade.

**Comment by horrokotoj** [comment]
Thanks for the response.
Up hill struggle this:
![image](https://user-images.githubusercontent.com/53189151/146459651-d4b4e15d-e202-42c0-82cd-f629b1b60dec.png)

Might this have to do with the fact that fact that "ppp" is not working?

**Comment by jacobgkau** [comment]
> Might this have to do with the fact that fact that "ppp" is not working?

No, point-to-point protocol is a very old standard meant to facilitate router-to-router communication and it is very unlikely your system actually needs to use it. This is just a package management issue.

What is the output of `apt policy network-manager network-manager-pptp network-manager-pptp-gnome`? (We can actually forget about the `php` packages, those were on the other user's machine but they weren't in your earlier screenshot.)

Also, please copy/paste your output into a message inside of code blocks (\`\`\`), that will make it easier to work with and to index the issue.

---

System76 customers can reach out to [support](https://support.system76.com/) for technical assistance. For non-System76 hardware, you can seek community support on [Reddit](https://reddit.com/r/pop_os/) or [Mattermost](https://chat.pop-os.org).

**Comment by horrokotoj** [comment]
Alright.


```leo@pop-os:~/packages$ apt policy network-manager network-manager-pptp network-manager-pptp-gnome
network-manager:
  Installed: 1.30.0-1ubuntu3
  Candidate: 1.30.0-1ubuntu3
  Version table:
 *** 1.30.0-1ubuntu3 500
        500 http://us.archive.ubuntu.com/ubuntu hirsute/main amd64 Packages
        100 /var/lib/dpkg/status
network-manager-pptp:
  Installed: 1.2.8-3
  Candidate: 1.2.8-3
  Version table:
 *** 1.2.8-3 500
        500 http://us.archive.ubuntu.com/ubuntu hirsute/main amd64 Packages
        100 /var/lib/dpkg/status
network-manager-pptp-gnome:
  Installed: 1.2.8-3
  Candidate: 1.2.8-3
  Version table:
 *** 1.2.8-3 500
        500 http://us.archive.ubuntu.com/ubuntu hirsute/main amd64 Packages
        100 /var/lib/dpkg/status```

**Comment by horrokotoj** [comment]
This is what ```apt policy network-manager network-manager-pptp network-manager-pptp-gnome``` gave.

Does it tell you anything?

**Comment by jacobgkau** [comment]
All of those are still on their hirsute (21.04) versions, and your system has 21.04 sources present. Let's try getting `ppp` back down to the 21.04 version.

```
sudo apt install ppp=2.4.7-2+4.1ubuntu8
```

What output does that show?

If your system has a Recovery partition, booting into that and performing a Refresh Install will be a faster and easier way to resolve this than troubleshooting the dependencies. Does your system have a Recovery partition?

Please also answer my question from before:

> Did you previously attempt to upgrade, have a failed upgrade, or cancel an upgrade before you saw what's in the first screenshot?

**Comment by horrokotoj** [comment]
```sudo apt install ppp=2.4.7-2+4.1ubuntu8``` 
results in:
```Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
You might want to run 'apt --fix-broken install' to correct these.
The following packages have unmet dependencies.
 network-manager : Depends: libnm0 (= 1.30.0-1ubuntu3) but 1.32.12-0ubuntu1 is to be installed
E: Unmet dependencies. Try 'apt --fix-broken install' with no packages (or specify a solution).```

To my knowledge I do not have a Recovery partition. I have not set up one my self any how.

To answer your question from before that I somehow missed:
I started to download the upgrade to 20.10 via "OS Upgrade & Recoery" under "Settings" whithout starting the upgrade process.
A while later I opened Pop!_Shop and updated all available updates. Somewhere during those updates there was an error. I missed to save that error message though. After a reboot I went to "OS Upgrade & Recoery" again and was greated with what is in my first screen shot. Following the instructions ```sudo dpkg --configure -a``` was the first line to give an unexpected error.

**Comment by jacobgkau** [comment]
Just to be clear, we are talking about 21.10, not 20.10. 20.10 is from October 2020 and has been end of support for some time.

> I started to download the upgrade to 20.10 via "OS Upgrade & Recoery" under "Settings" whithout starting the upgrade process.
A while later I opened Pop!_Shop and updated all available updates.
> ...
> After a reboot I went to "OS Upgrade & Recoery" again

Here is where the problem happened:

- When you started downloading the upgrade, pop-upgrade updated your apt sources from 21.04 to 21.10 in order to fetch the new release's packages.
- When you opened the Pop!_Shop, the updates that you saw available were for 21.10, not 21.04; however, the Pop!_Shop is not equipped to handle release upgrades (that is pop-upgrade's job), so you saw an error.
- When you rebooted, you effectively told pop-upgrade to cancel the release upgrade, and it attempted to self-update itself again on the next boot, which is all normal; however, https://github.com/pop-os/upgrade/issues/193 caused it to self-update to the 21.10 release instead of 21.04, which left your system in a mixed state.

So https://github.com/pop-os/upgrade/pull/232 will address part of the problem here, but the Pop!_Shop also needs to not prompt (and ideally not allow) for installing updates while pop-upgrade is working. We have an issue open at https://github.com/pop-os/upgrade/issues/168 regarding at least turning off Pop!_Shop notifications during the pop-upgrade process.

**Comment by jacobgkau** [comment]
> To my knowledge I do not have a Recovery partition. I have not set up one my self any how.

This is not something that requires manual setup and not something that requires advanced knowledge. In the OS Upgrade & Recovery page, do you have an "OS Recovery" section? (If it's there, it should have a Refresh button.)

Assuming that's not present, to fix the dependency issue, you'll need to work back through the dependencies and continue appending them to the apt command until you're specifying a full solution. For example, take the previous apt command I provided, and add the package name and required version number from the error message you got back:

```
sudo apt install ppp=2.4.7-2+4.1ubuntu8 libnm0=1.30.0-1ubuntu3
```

Continue doing this until apt succeeds, or gives a different type of error message (such as "version was not found" or "unable to locate.")

(If you boot from a Pop!_OS flash drive, the installer should also offer you the option to refresh, if you'd rather do that.)

**Comment by horrokotoj** [comment]
Yes, I meant 21.10.

Alright, that is definitely what happned. 

So is there a list of versions I need to go through? And should I be going backwards or forwards?

I ran ``` sudo apt install ppp=2.4.7-2+4.1ubuntu8 libnm0=1.30.0-1ubuntu3 ``` and received 
```
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following packages will be DOWNGRADED:
  libnm0 ppp
0 to upgrade, 0 to newly install, 2 to downgrade, 0 to remove and 7 not to upgrade.
1 not fully installed or removed.
Need to get 740 kB of archives.
After this operation, 71,7 kB disk space will be freed.
Do you want to continue? [Y/n] y
Get:1 http://us.archive.ubuntu.com/ubuntu hirsute/main amd64 ppp amd64 2.4.7-2+4.1ubuntu8 [328 kB]
Get:2 http://us.archive.ubuntu.com/ubuntu hirsute/main amd64 libnm0 amd64 1.30.0-1ubuntu3 [413 kB]
Fetched 740 kB in 1s (774 kB/s)   
dpkg: warning: downgrading ppp from 2.4.9-1+1ubuntu1 to 2.4.7-2+4.1ubuntu8
dpkg: warning: files list file for package 'ppp' missing; assuming package has n
o files currently installed
(Reading database ... 508069 files and directories currently installed.)
Preparing to unpack .../ppp_2.4.7-2+4.1ubuntu8_amd64.deb ...
Unpacking ppp (2.4.7-2+4.1ubuntu8) over (2.4.9-1+1ubuntu1) ...
Setting up ppp (2.4.7-2+4.1ubuntu8) ...
dpkg: warning: downgrading libnm0:amd64 from 1.32.12-0ubuntu1 to 1.30.0-1ubuntu3
(Reading database ... 508179 files and directories currently installed.)
Preparing to unpack .../libnm0_1.30.0-1ubuntu3_amd64.deb ...
Unpacking libnm0:amd64 (1.30.0-1ubuntu3) over (1.32.12-0ubuntu1) ...
Setting up libnm0:amd64 (1.30.0-1ubuntu3) ...
Processing triggers for man-db (2.9.4-2) ...
Processing triggers for libc-bin (2.34-0ubuntu3) ...
```
It seems like it managed to install that version.

``` sudo apt update``` then returned
```
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following packages will be DOWNGRADED:
  libnm0 ppp
0 to upgrade, 0 to newly install, 2 to downgrade, 0 to remove and 7 not to upgrade.
1 not fully installed or removed.
Need to get 740 kB of archives.
After this operation, 71,7 kB disk space will be freed.
Do you want to continue? [Y/n] y
Get:1 http://us.archive.ubuntu.com/ubuntu hirsute/main amd64 ppp amd64 2.4.7-2+4.1ubuntu8 [328 kB]
Get:2 http://us.archive.ubuntu.com/ubuntu hirsute/main amd64 libnm0 amd64 1.30.0-1ubuntu3 [413 kB]
Fetched 740 kB in 1s (774 kB/s)   
dpkg: warning: downgrading ppp from 2.4.9-1+1ubuntu1 to 2.4.7-2+4.1ubuntu8
dpkg: warning: files list file for package 'ppp' missing; assuming package has n
o files currently installed
(Reading database ... 508069 files and directories currently installed.)
Preparing to unpack .../ppp_2.4.7-2+4.1ubuntu8_amd64.deb ...
Unpacking ppp (2.4.7-2+4.1ubuntu8) over (2.4.9-1+1ubuntu1) ...
Setting up ppp (2.4.7-2+4.1ubuntu8) ...
dpkg: warning: downgrading libnm0:amd64 from 1.32.12-0ubuntu1 to 1.30.0-1ubuntu3
(Reading database ... 508179 files and directories currently installed.)
Preparing to unpack .../libnm0_1.30.0-1ubuntu3_amd64.deb ...
Unpacking libnm0:amd64 (1.30.0-1ubuntu3) over (1.32.12-0ubuntu1) ...
Setting up libnm0:amd64 (1.30.0-1ubuntu3) ...
Processing triggers for man-db (2.9.4-2) ...
Processing triggers for libc-bin (2.34-0ubuntu3) ...
```
So it seems like it did not fully resolve the issue.

**Comment by jacobgkau** [comment]
The output from that `apt install` command actually indicates it did solve the dependency issue. The next one is unrelated, and likely just means the Pop!_Shop happened to be checking for updates at the same time you tried to run `sudo apt update` (possibly because it noticed the change from the previous command.) Can you try running it again?

**Comment by horrokotoj** [comment]
OMG, this is the best new I have seen so far!!
```
Hit:1 http://ppa.launchpad.net/system76/pop/ubuntu hirsute InRelease
Hit:2 http://us.archive.ubuntu.com/ubuntu hirsute InRelease                                        
Get:3 http://us.archive.ubuntu.com/ubuntu hirsute-security InRelease [110 kB]
Hit:4 http://apt.pop-os.org/proprietary hirsute InRelease 
Hit:5 http://apt.pop-os.org/release impish InRelease      
Get:6 http://us.archive.ubuntu.com/ubuntu hirsute-updates InRelease [115 kB]
Get:7 http://us.archive.ubuntu.com/ubuntu hirsute-backports InRelease [101 kB]
Get:8 http://us.archive.ubuntu.com/ubuntu hirsute-security/main amd64 DEP-11 Metadata [9 692 B]
Get:9 http://us.archive.ubuntu.com/ubuntu hirsute-security/universe amd64 DEP-11 Metadata [7 100 B]
Get:10 http://us.archive.ubuntu.com/ubuntu hirsute-updates/main amd64 DEP-11 Metadata [97,7 kB]
Get:11 http://us.archive.ubuntu.com/ubuntu hirsute-updates/universe amd64 DEP-11 Metadata [61,0 kB]
Get:12 http://us.archive.ubuntu.com/ubuntu hirsute-updates/multiverse amd64 DEP-11 Metadata [944 B]
Get:13 http://us.archive.ubuntu.com/ubuntu hirsute-backports/universe amd64 DEP-11 Metadata [9 348 B]
Fetched 512 kB in 1s (426 kB/s)                  
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
7 packages can be upgraded. Run 'apt list --upgradable' to see them.
```

**Comment by jacobgkau** [comment]
Before you install any more updates, you will want to run at least the first command from this article: https://support.system76.com/articles/upgrade-pop#repairing-upgrade-errors 

```
sudo rm /etc/apt/sources.list.d/pop-os-ppa.sources
```

If your `apt update` output still had any `impish` sources present, this command should remove those, leaving you fully on hirsute (21.04).

**Comment by jacobgkau** [comment]
I can see from the output you provided that the above command is needed and should work. So do that, make sure no other updates from Hirsute are available:

```
sudo rm /etc/apt/sources.list.d/pop-os-ppa.sources
sudo apt update
sudo apt full-upgrade
```

And if that shows no errors, reboot and then try the upgrade again (letting it finish this time):

```
pop-upgrade release upgrade
```

**Comment by horrokotoj** [comment]
I am sorry, I might have jumped the gun.
I ran
``` sudo rm /etc/apt/sources.list.d/pop-os-ppa.sources
systemctl restart pop-upgrade
pop-upgrade release upgrade ``` from the article that you linked to.

Result ended in ``` Release upgrade status: systems are go for launch: reboot now ```

**Comment by jacobgkau** [comment]
That's fine, just reboot at this point to actually install the upgrade.

**Comment by horrokotoj** [comment]
After a reboot I was able to download 21.10. I then installed it during a reboot. It looked sketchy but seems like it went fine.
Everything seems to be running smoothly now. 

I am so greatful for your help.

Have a great weekend!
