### ISSUE TITLE
"Syncing recovery image to disk" message does not go away

### ISSUE THREAD

**Issue by jacobgkau** [pop-os/upgrade#237]
This was not caused by https://github.com/pop-os/upgrade/pull/232.

When upgrading the OS via GUI, the Recovery partition is correctly updated first, but the "Syncing recovery image to disk" status message does not go away when pop-upgrade moves on to the actual release upgrade. The Recovery image does appear to sync (it's useable), but this has confused some users into cancelling the upgrade (causing further problems due to https://github.com/pop-os/upgrade/issues/193.)

Example screenshot: https://chat.pop-os.org/pop-os/pl/ufj3tdddoinddkdb9sppobr18h

**Comment by mmstick** [comment]
Are there any logs from an upgrade that did this? Looking for `UiEvent` messages to see if an event was missed.

**Comment by jacobgkau** [comment]
This is still occurring on master but is not currently occurring on `schedule` in a 20.04 EFI VM, so I've linked that PR to close this.
