### ISSUE TITLE
"most current" may sound more natural as "latest"

### ISSUE THREAD

**Issue by ninjamar** [pop-os/upgrade#252]
I just upgraded to PopOS 21.10 and the os upgrade and recovery menu inside settings says "You are running the most current Pop!_OS version". I think this could be changed to "You are running the latest Pop!_OS version". I think that the first message seems weird.
![](https://ninjamar.dev/assets/images/grammar.png)

**Comment by jacobgkau** [comment]
"most current" and "latest" are synonyms; "most current" is certainly not grammatically incorrect.

**Comment by ninjamar** [comment]
ok
