### ISSUE TITLE
22.04 Release Notes

### ISSUE THREAD

**Issue by jackpot51** [pop-os/upgrade#276]
- Based on Ubuntu 22.04
- GNOME 42
- Mesa 22
- Debian packaging of firefox

**Comment by WatchMkr** [comment]
* Pipewire replaces Pulseaudio audio system in Pop!_OS 22.04 LTS
* Dark and light modes can have independent backgrounds
* New upgrade and upgrade installation options in Settings > OS Upgrade and Recovery
** To reduce distractions, update notifications are now set to show weekly and can be set to daily or monthly
** Upgrades can be scheduled and installed automatically
* Settings for Desktop Options, Background, Appearance, Dock, and Workspaces are now directly searchable in Launcher
* Installed nvidia drivers are now visible in Pop!_Shop and older drivers are available to install

**Comment by mmstick** [comment]
- Pop System Updater: automatic system update and update scheduling
- System76 Scheduler: CPU and process scheduling optimizations
- System76 Power: CPU scaling governor improvements
- New Support panel in GNOME Settings and pop-support tool
- Pop Shop now uninstallable / GNOME Software installable
- Limited journald log max disk capacity to 1GB
- Added [Pop robot face](https://github.com/pop-os/default-settings/commit/77e14a2847fada0e979b1bb519e4f291b7bb3246)

**Comment by 13r0ck** [comment]
- Reduce cosmic logging, which technically also means more performant.
    - https://github.com/pop-os/cosmic-workspaces/pull/63
    - https://github.com/pop-os/cosmic-workspaces/pull/62
    - https://github.com/pop-os/cosmic-dock/pull/133
    - https://github.com/pop-os/cosmic/pull/331
- Plymouth translations, and fix for rotated HIDPI displays
    - https://github.com/pop-os/plymouth/pull/4
- Cosmic-workspaces
    - Fix location of workspace picker box on secondary displays
    - Fix scaling of workspace picker on dispalys of different respoutions
    - Increase performance
    - Fix alignment on HIDPI displays
    - Make OSD picker smaller and vertical
    - https://github.com/pop-os/cosmic-workspaces/pull/56
    - https://github.com/pop-os/cosmic-workspaces/pull/54

**Comment by isantop** [comment]
* Updated Shell Theme for GNOME 42
* SVG-based icons instead of PNG
* Rebased Pop_Shop on upstream (pending)
