### ISSUE TITLE
Kernel Update broke my install

### ISSUE THREAD

**Issue by jsj1027** [pop-os/upgrade#28]
Not sure if this is the right place but just updated to kernel 5.0.0.16 from 5.0.0.15 using apt install.

Now I can not login to my pop-os install. Gives an automatic auth error. My password is the same I checked with the recovery mode. More of what happened is outlined here. 

https://old.reddit.com/r/pop_os/comments/by2055/help_system_broken_1904/

**Comment by jsj1027** [comment]
Fix posted to the same reddit thread. But will say it here as well.

Somehow the update uninstalled the pop-desktop. Reddit user /u/derp0mattic pointed this out. After I installed it, things worked again.

**Comment by mmstick** [comment]
This isn't related to the upgrade daemon project, so I'm going to close this.
