### ISSUE TITLE
Failing to upgrade due to GDM dependency

### ISSUE THREAD

**Issue by jacobgkau** [pop-os/upgrade#281]
I'm getting a failure during the offline portion of the upgrade in a 21.10 EFI VirtualBox VM. This is occurring on the master branch (ddcabc4).

Package list before upgrade: [packages-before-fail.txt](https://github.com/pop-os/upgrade/files/8545208/packages-before-fail.txt)
pop-upgrade daemon log before upgrade: [upgrade-daemon-fail.txt](https://github.com/pop-os/upgrade/files/8545209/upgrade-daemon-fail.txt)
Offline upgrade log: [upgrade-fail.log](https://github.com/pop-os/upgrade/files/8545210/upgrade-fail.log)
Package list after upgrade: [packages-after-fail.txt](https://github.com/pop-os/upgrade/files/8545211/packages-after-fail.txt)

After the system "completes" the offline upgrade and reboots back into the OS, most of my packages are still on Impish, but my sources are pointing to Jammy. The issue looks like something to do with a GDM dependency.

**Comment by bflanagin** [comment]
I had the same thing occur on my work laptop. I was able to work around the issue by setting the sources back to impish, running `apt update && apt -f install` and then running pop-upgrade again. The second time around everything worked as expected.

**Comment by jackpot51** [comment]
This looks like the problem, @mmstick do you have any ideas about it?

```
Apr 22 18:01:51 pop-os pop-upgrade[2162]: [INFO ] daemon/mod.rs:1104: installing latest version of `pop-upgrade`, which will restart the daemon
Apr 22 18:01:51 pop-os pop-upgrade[2743]: Reading package lists...
Apr 22 18:01:51 pop-os pop-upgrade[2743]: Building dependency tree...
Apr 22 18:01:51 pop-os pop-upgrade[2743]: Reading state information...
Apr 22 18:01:51 pop-os pop-upgrade[2743]: Correcting dependencies... failed.
Apr 22 18:01:51 pop-os pop-upgrade[2743]: The following packages have unmet dependencies:
Apr 22 18:01:51 pop-os pop-upgrade[2743]:  gdm3 : Depends: gir1.2-gdm-1.0 (= 41~rc-0ubuntu2pop0~1634915133~21.10~cf40258) but 42.0-1ubuntu6pop1~1650301427~22.04~2055533 is installed
Apr 22 18:01:51 pop-os pop-upgrade[2743]:         Depends: libgdm1 (= 41~rc-0ubuntu2pop0~1634915133~21.10~cf40258) but 42.0-1ubuntu6pop1~1650301427~22.04~2055533 is installed
Apr 22 18:01:51 pop-os pop-upgrade[2743]:  gnome-control-center : Depends: gnome-control-center-data (< 1:41) but 1:41.4-1ubuntu12pop1~1650584225~22.04~197d500 is installed
Apr 22 18:01:51 pop-os pop-upgrade[2743]:  gnome-settings-daemon : Depends: gnome-settings-daemon-common (= 40.0.1-1ubuntu3pop0~1639691325~21.10~3bcd31b) but 42.1-1ubuntu1pop0~1649081298~22.04~192b1be is installed
Apr 22 18:01:51 pop-os pop-upgrade[2743]:  systemd : Depends: libsystemd0 (= 248.3-1ubuntu8.2pop0~1647542931~21.10~ab7b8e3) but 249.11-0ubuntu3pop0~1650312774~22.04~cecf6af is installed
Apr 22 18:01:51 pop-os pop-upgrade[2743]: E: Error, pkgProblemResolver::Resolve generated breaks, this may be caused by held packages.
Apr 22 18:01:51 pop-os pop-upgrade[2743]: E: Unable to correct dependencies
```

**Comment by jackpot51** [comment]
Please try with `master` staging added, ensuring you have this `systemd`: https://github.com/pop-os/repo-release/pull/103

**Comment by jacobgkau** [comment]
> Please try with `master` staging added, ensuring you have this `systemd`: [pop-os/repo-release#103](https://github.com/pop-os/repo-release/pull/103)

I added the master branch, installed pop-upgrade, and ran the upgrade (which pulled in systemd during the "updating current release" portion). The offline portion still exited early.

Would a reboot between installing that systemd update and running pop-upgrade be necessary?

**Comment by jacobgkau** [comment]
It looked like systemd wasn't being updated because the staging branch was being removed by pop-upgrade, trying again now that systemd has been released.

**Comment by jacobgkau** [comment]
I'm not seeing the issue on a completely fresh install, so it's probably something to do with one of the packages added to the problem install. The packages added were: `wine steam kdenlive audacity lmms musescore3`

We have reports that `steam`, `lmms`, and `audacity` alone don't cause the issue, I'm trying an upgrade with just `wine` next.

**Comment by jacobgkau** [comment]
Confirmed the issue happens with only `wine`, Michael has also recreated the issue. We're testing adding additional packages to the prerequisites list in the offline script.
