### ISSUE TITLE
PulseEffects (deb) not working anymore

### ISSUE THREAD

**Issue by Odin000** [pop-os/upgrade#285]
after upgrading to 20.04 LTS, my PulseEffects (deb) was removed.
I tried to install it again but the shop breaks each time I try to install it again.

PS. PulseEffects (flatpak) never worked for me on Pop_Os!

**Comment by mmstick** [comment]
I'm using the PulseEffects flatpak on 22.04 without issue. Is there something I can check that's not working?

**Comment by mmstick** [comment]
Ah I see this is referring to PulseAudio PulseEffects. The software to use in 22.04 is EasyEffects.
