### ISSUE TITLE
PopOS after update from 21.10 to 22.04 destroyed Plasma

### ISSUE THREAD

**Issue by aleOS2** [pop-os/upgrade#291]
Hi.
Yesterday i received a notification about update to popOS 22.04. I use Plasma.

I have to update, rebooted and SDDM can't find the theme.
![IMG_20220430_174727_909](https://user-images.githubusercontent.com/65780895/166113092-84a58756-71c7-428c-8cb6-792e9555c62e.jpg)
![IMG_20220430_174710_895](https://user-images.githubusercontent.com/65780895/166113094-2b39a127-ee86-4a0d-b26e-6ab381d812d2.jpg)

And i see that the Desktop env. aviables are only Pop and Pop Wayland.

![IMG_20220430_174713_496](https://user-images.githubusercontent.com/65780895/166113120-c403ddf0-9754-487e-8d79-60fe1ac0717d.jpg)

I think popOS have removed Plasma.
To fix that i used Timeshift to return to 21.10 but after a reboot it auto destroy.

I don't think this a normal things to do.
I'm thinking about change distro..
And also pop shell crashed

MY PC SPECS:
AMD Ryzen 5 5600G
MSI b550 gaming plus 
Ram Ballistix 3200mhz 8x2
Nvme Samsung 970 evo plus 1TB

**Comment by jacobgkau** [comment]
> To fix that i used Timeshift to return to 21.10 but after a reboot it auto destroy.

What does this mean? Is your Timeshift restore not working, or was the system broken at the time of the Timeshift restore before the upgrade?

> I think popOS have removed Plasma.

Can you try running `apt policy plasma-desktop` after the upgrade to check if it's installed?

**Comment by aleOS2** [comment]
Sorry but i have removed pop the next day. Thanks anyway

**Comment by jacobgkau** [comment]
Closing if we can't troubleshoot or collect any more information.
