### ISSUE TITLE
`pop-upgrade release upgrade` silently removes a lot of packages from system

### ISSUE THREAD

**Issue by Flashwalker** [pop-os/upgrade#306]
**Distribution (run `cat /etc/os-release`):**
 ```
NAME="Pop!_OS"
VERSION="20.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.04 LTS"
VERSION_ID="20.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
LOGO=distributor-logo-pop-os
```
 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
```
$ apt policy pop-upgrade
pop-upgrade:
  Установлен: 1.0.0~1654884321~20.04~a74793e
  Кандидат:   1.0.0~1657305150~22.04~036e99b
  Таблица версий:
     1.0.0~1657305150~22.04~036e99b 1001
       1001 http://apt.pop-os.org/release jammy/main amd64 Packages
 *** 1.0.0~1654884321~20.04~a74793e 100
        100 /var/lib/dpkg/status
```

**Issue/Bug Description:**
# I found a lot of applications was removed silently from my system by `pop-upgrade release upgrade`

And i do not even know what and how many was removed...

Why you guys do it so not user friendly?

# How can i find what was removed? during `pop-upgrade release upgrade`?:
```
...
Event: removing deprecated and/or conflicting packages
...
```
### Is there a log or something?

**Steps to reproduce (if you know):**
1. `sudo apt update`
2. `sudo apt full-upgrade` # we ok ere, `apt` informing us what changes will be made
3. `sudo pop-upgrade release upgrade` # silently remove a lot packages at this step

**Expected behavior:**
Always give user to decide what to be removed or not.
Notify about deprecated before silently purge it.

**Other Notes:**
It is a very bad idea to remove applications silently. You guys making a distro for users or not? Why so not user friendly?
The worst practice to make distro.

**Comment by jacobgkau** [comment]
> Always give user to decide what to be removed or not.

This is not always possible, it can essentially mean allowing the user to decide whether the upgrade is successful or not in some cases. Providing notice is another topic.

> After all upgrade done i'm still have poup notification "Upgrade available 22.04"... Nice work, guys!1

It sounds like the upgrade is not actually complete. Please provide the output of `sudo apt update` and `cat /etc/os-release` to confirm.

Please keep in mind that GitHub is not a support forum. If you own System76 hardware, you can open a [support ticket](https://support.system76.com) for professional assistance. Otherwise, you are welcome to seek community assistance on the [Mattermost chat room](https://chat.pop-os.org/pop-os) or the [subreddit](https://old.reddit.com/r/pop_os/).

Please also keep the [Pop!_OS code of conduct](https://github.com/pop-os/code-of-conduct) in mind and be considerate when choosing the tone of your comments.

**Comment by Flashwalker** [comment]
> upgrade is successful

Depends on what you call successful upgrade

**Remove 400+ hundred packages and libs from system wich are absolutely has no conflict**  
**and output:**
```
...
Event: simulating upgrade
Event: new release is ready to install
Release upgrade status: systems are go for launch: reboot now
```
**and nothing happens, no upgrade completed**  
**notifications about new release are still popping up**
**and further attempts to run the upgrade give an error...**

That's what you call "successful upgrade"? ...


[facepalm.jpg]

**Comment by Flashwalker** [comment]
Sometimes bad tone guys needed for good code refactoring

**Comment by leviport** [comment]
>Sometimes bad tone guys are needed for good code refactoring

Even if that were true, this is not one of those times. If you continue to be condescending and disrespectful, you will no longer be permitted to interact with our repositories.

**Comment by Flashwalker** [comment]
sudo apt update:

```
sudo apt update
Hit:1 http://ppa.launchpad.net/system76/pop/ubuntu focal InRelease
Hit:2 http://us.archive.ubuntu.com/ubuntu focal InRelease
Hit:3 http://apt.pop-os.org/proprietary focal InRelease
Hit:4 http://us.archive.ubuntu.com/ubuntu focal-security InRelease
Hit:5 http://us.archive.ubuntu.com/ubuntu focal-updates InRelease
Ign:6 http://apt.pop-os.org/release focal InRelease
Get:7 http://us.archive.ubuntu.com/ubuntu focal-backports InRelease [108 kB]
Err:8 http://apt.pop-os.org/release focal Release        
  404  Not Found [IP: 13.33.243.81 80]
Reading package lists... Done                            
E: The repository 'http://apt.pop-os.org/release focal Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

cat /etc/os-release
```
NAME="Pop!_OS"
VERSION="20.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.04 LTS"
VERSION_ID="20.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
LOGO=distributor-logo-pop-os
```


sudo pop-upgrade release upgrade
```
[sudo] пароль для deniz: 
checking if pop-upgrade requires an update
Current Release: 20.04
Upgrading to: 22.04
New version available: 11
Event: updating package lists
Release upgrade status: release upgrade aborted: failed to update package lists for the current release
```

**Comment by Flashwalker** [comment]
Even via proxy it failss again:
```
sudo pop-upgrade release upgrade
checking if pop-upgrade requires an update
Current Release: 20.04
Upgrading to: 22.04
New version available: 11
Event: updating package lists
Event: upgrading packages for the current release
Fetched (1/14): libldb2_2%3a2.2.3-0ubuntu0.20.04.3_amd64.deb
Fetched (2/14): winbind_2%3a4.13.17~dfsg-0ubuntu1.20.04.1_amd64.deb
Fetched (3/14): samba_2%3a4.13.17~dfsg-0ubuntu1.20.04.1_amd64.deb
Fetched (4/14): samba-common-bin_2%3a4.13.17~dfsg-0ubuntu1.20.04.1_amd64.deb
Fetched (5/14): samba-dsdb-modules_2%3a4.13.17~dfsg-0ubuntu1.20.04.1_amd64.deb
Fetched (6/14): samba-libs_2%3a4.13.17~dfsg-0ubuntu1.20.04.1_amd64.deb
Fetched (7/14): libsmbclient_2%3a4.13.17~dfsg-0ubuntu1.20.04.1_amd64.deb
Fetched (8/14): python3-ldb_2%3a2.2.3-0ubuntu0.20.04.3_amd64.deb
Fetched (9/14): libsnmp35_5.8+dfsg-2ubuntu2.4_amd64.deb
Fetched (10/14): python3-samba_2%3a4.13.17~dfsg-0ubuntu1.20.04.1_amd64.deb
Fetched (11/14): libwbclient0_2%3a4.13.17~dfsg-0ubuntu1.20.04.1_amd64.deb
Fetched (12/14): libsnmp-base_5.8+dfsg-2ubuntu2.4_all.deb
Fetched (13/14): samba-vfs-modules_2%3a4.13.17~dfsg-0ubuntu1.20.04.1_amd64.deb
Fetched (14/14): samba-common_2%3a4.13.17~dfsg-0ubuntu1.20.04.1_all.deb
Event: fetching updated packages for the current release
Progress: 0%
Progress: 2%
Unpacking libldb2:amd64 (2:2.2.3-0ubuntu0.20.04.3) over (2:2.2.3-0ubuntu0.20.04.2)
Progress: 4%
Setting up libldb2:amd64
Progress: 5%
Progress: 7%
Progress: 9%
Unpacking python3-ldb (2:2.2.3-0ubuntu0.20.04.3) over (2:2.2.3-0ubuntu0.20.04.2)
Progress: 11%
Setting up python3-ldb
Progress: 12%
Progress: 14%
Progress: 16%
Unpacking samba-vfs-modules:amd64 (2:4.13.17~dfsg-0ubuntu1.20.04.1) over (2:4.13.17~dfsg-0ubuntu0.21.04.2)
Progress: 18%
Progress: 19%
Unpacking python3-samba (2:4.13.17~dfsg-0ubuntu1.20.04.1) over (2:4.13.17~dfsg-0ubuntu0.21.04.2)
Progress: 21%
Progress: 23%
Unpacking samba (2:4.13.17~dfsg-0ubuntu1.20.04.1) over (2:4.13.17~dfsg-0ubuntu0.21.04.2)
Progress: 25%
Progress: 26%
Unpacking winbind (2:4.13.17~dfsg-0ubuntu1.20.04.1) over (2:4.13.17~dfsg-0ubuntu0.21.04.2)
Progress: 28%
Progress: 30%
Unpacking samba-common-bin (2:4.13.17~dfsg-0ubuntu1.20.04.1) over (2:4.13.17~dfsg-0ubuntu0.21.04.2)
Progress: 32%
Progress: 33%
Unpacking samba-common (2:4.13.17~dfsg-0ubuntu1.20.04.1) over (2:4.13.17~dfsg-0ubuntu0.21.04.2)
Progress: 35%
Progress: 37%
Unpacking samba-dsdb-modules:amd64 (2:4.13.17~dfsg-0ubuntu1.20.04.1) over (2:4.13.17~dfsg-0ubuntu0.21.04.2)
Progress: 39%
Progress: 40%
Unpacking libwbclient0:amd64 (2:4.13.17~dfsg-0ubuntu1.20.04.1) over (2:4.13.17~dfsg-0ubuntu0.21.04.2)
Progress: 42%
Setting up libwbclient0:amd64
Progress: 44%
Progress: 46%
Progress: 47%
Unpacking samba-libs:amd64 (2:4.13.17~dfsg-0ubuntu1.20.04.1) over (2:4.13.17~dfsg-0ubuntu0.21.04.2)
Progress: 49%
Setting up samba-libs:amd64
Progress: 51%
Progress: 53%
Progress: 54%
Unpacking libsmbclient:amd64 (2:4.13.17~dfsg-0ubuntu1.20.04.1) over (2:4.13.17~dfsg-0ubuntu0.21.04.2)
Progress: 56%
Setting up libsmbclient:amd64
Progress: 58%
Progress: 60%
Progress: 61%
Unpacking libsnmp-base (5.8+dfsg-2ubuntu2.4) over (5.8+dfsg-2ubuntu2.3)
Progress: 63%
Setting up libsnmp-base
Progress: 65%
Progress: 67%
Progress: 68%
Unpacking libsnmp35:amd64 (5.8+dfsg-2ubuntu2.4) over (5.8+dfsg-2ubuntu2.3)
Progress: 70%
Setting up libsnmp35:amd64
Progress: 72%
Progress: 74%
Setting up samba-vfs-modules:amd64
Progress: 75%
Progress: 77%
Setting up samba-common
Progress: 79%
Progress: 81%
Setting up samba-dsdb-modules:amd64
Progress: 82%
Progress: 84%
Setting up python3-samba
Progress: 86%
Progress: 88%
Setting up samba-common-bin
Progress: 89%
Progress: 91%
Setting up samba
Progress: 93%
Progress: 95%
Setting up winbind
Progress: 96%
Progress: 98%
Processing triggers for systemd
Processing triggers for man-db
Processing triggers for libc-bin
Processing triggers for ufw
Release upgrade status: release upgrade aborted: failed to downgrade packages
```

**Comment by Flashwalker** [comment]
Damn, my system so broken now after this "upgrade" that even my proxy doesn't works anymore...

**Comment by mmstick** [comment]
Same as recommended by the [Debian manual](https://www.debian.org/releases/stable/i386/release-notes/ch-upgrading.en.html#system-status), you must remove all non-Ubuntu, non-Pop packages and repositories from the system to ensure the upgrade is successful. You're system seems to have some conflicting third party packages failing to downgrade to the Ubuntu/Pop version of those packages.

**Comment by Flashwalker** [comment]
> Same as recommended by the [Debian manual](https://www.debian.org/releases/stable/i386/release-notes/ch-upgrading.en.html#system-status), you must remove all non-Ubuntu, non-Pop packages and repositories from the system to ensure the upgrade is successful. Your system seems to have some conflicting third party packages failing to downgrade to the Ubuntu/Pop version of those packages.

So that's i'm talking about,
`pop-upgrade` silently broke my packages dependencies and now i have half-working conflicting system.
Obviously we need warning before doing things like this anf hope to get lucky.
It is bad idea, guys, to ruin user's system and then send him to RTFM

**Comment by Flashwalker** [comment]
According to the syslog `pop-upgrade` can't find your release repo behind a proxy:
```
Aug  1 22:34:59 smarttop pop-upgrade[33759]: Hit:5 http://us.archive.ubuntu.com/ubuntu focal-updates InRelease
Aug  1 22:34:59 smarttop pop-upgrade[33759]: Err:6 http://apt.pop-os.org/release focal Release
Aug  1 22:34:59 smarttop pop-upgrade[33759]:   404  Not Found [IP: 127.0.0.1 8118]
```

```

Aug  1 22:36:54 smarttop pop-upgrade[38204]: Hit:1 http://ppa.launchpad.net/system76/pop/ubuntu focal InRelease
Aug  1 22:36:54 smarttop pop-upgrade[38204]: Hit:2 http://us.archive.ubuntu.com/ubuntu focal InRelease
Aug  1 22:36:54 smarttop pop-upgrade[38204]: Hit:3 http://apt.pop-os.org/proprietary focal InRelease
Aug  1 22:36:54 smarttop pop-upgrade[38204]: Ign:4 http://apt-origin.pop-os.org/release focal InRelease
Aug  1 22:36:54 smarttop pop-upgrade[38204]: Hit:5 http://us.archive.ubuntu.com/ubuntu focal-updates InRelease
Aug  1 22:36:55 smarttop pop-upgrade[38204]:   404  Not Found [IP: 127.0.0.1 8118]
```

**Comment by Flashwalker** [comment]
Trying without proxy (after several attempts with proxy and vpn) gave me downgrading works, but fails on needed user interaction
full log: https://fars.ee/egc8

that's why interactions are needed, guys

**Comment by Flashwalker** [comment]
After hours of manually resolving dependency conflicts, I finally got the release installed.
This was the most difficult upgrade I've ever made with Linux.

**Comment by Flashwalker** [comment]
Now i need several hours to get back removed apps...

**Comment by leviport** [comment]
Glad you fixed it. Sounds to me like the main issue was a network problem. I'm going to close this, but we can reopen it if any other reports crop up. So far you're the only one.

>TODO: Never install pop-os again.

That's not a useful or productive anecdote. I understand that you're frustrated, but please channel your frustrations elsewhere.

**Comment by Flashwalker** [comment]
ok, sorry

**Comment by silverhadch** [comment]
@leviport 

Pls reopen allot of maunally installed .deb packages like BlueJ and MEGASync and my entire KDE Plasma were wiped. I reinstalled but thats a bad User experience.

**Comment by mmstick** [comment]
@silverhadch It is expected, as mentioned in the upgrade dialog. Packages without a repository will be auto-removed to prevent upgrades from breaking.

**Comment by silverhadch** [comment]
> @silverhadch It is expected, as mentioned in the upgrade dialog. Packages without a repository will be auto-removed to prevent upgrades from breaking.

Well Plasma is inside the Ubuntu repos and does locking a package prevent this?

**Comment by jacobgkau** [comment]
> Well Plasma is inside the Ubuntu repos and does locking a package prevent this?

If it wasn't removed due to being orphaned, then it would likely be because of package conflict or because it was autoremovable (originally installed as a dependency of something else that's now gone).

"Locking" a package would likely prevent pop-upgrade from proceeding if it's not able to remove a package that it thinks it needs to remove.

I want to mention we are doing a little bit of manual removal of GNOME components for the transition from 22.04 to 24.04 specifically. I wouldn't expect that to affect KDE packages, but it could be relevant if we were to dig into debugging whatever you ran into.

**Comment by silverhadch** [comment]
> > Well Plasma is inside the Ubuntu repos and does locking a package prevent this?
> 
> If it wasn't removed due to being orphaned, then it would likely be because of package conflict or because it was autoremovable (originally installed as a dependency of something else that's now gone).
> 
> "Locking" a package would likely prevent pop-upgrade from proceeding if it's not able to remove a package that it thinks it needs to remove.
> 
> I want to mention we are doing a little bit of manual removal of GNOME components for the transition from 22.04 to 24.04 specifically. I wouldn't expect that to affect KDE packages, but it could be relevant if we were to dig into debugging whatever you ran into.

Well i was aware of that happening but why did it take Plasma with it and to note not everything got taken only like half the packages of Plasma were still there. All my manually via Ediy or whatever its called .deb packages were removed. And GDM and POP Desktop (which isnt suprising since thats the point but i like GDM as its currently the only DM that has smooth Plymouth transition and isnt overly cramped and complicated like cosmic greeter is.)

**Comment by mmstick** [comment]
You'd have to check the apt logs on the system to see why apt determined that it needed to remove plasma.

**Comment by silverhadch** [comment]
> You'd have to check the apt logs on the system to see why apt determined that it needed to remove plasma.

About that.... uhhh i wiped them already 😅

**Comment by Fe3000** [comment]
Hi! I have the upgrade  from POP OS 22.04 to 24.04 available for me and I am wondering will the upgrade fully remove user installed apps? I am not a power user so it would take a long time to add all the apps back.
Or will the final step of the upgrade automatically re-install the removed packages/apps?

`Same as recommended by the [Debian manual](https://www.debian.org/releases/stable/i386/release-notes/ch-upgrading.en.html#system-status)` this Debian page is not available anymore. Is there any more information or instructions regarding this?

**Comment by jacobgkau** [comment]
> Hi! I have the upgrade from POP OS 22.04 to 24.04 available for me and I am wondering will the upgrade fully remove user installed apps?

Any apps you installed via Flatpak will remain installed. For "not a power user," selecting the Flatpak option (often the default) from the Pop!_Shop/COSMIC Store when installing apps is going to provide you with the easiest and most reliable experience.

Any apps you installed from the default Pop!_OS and Ubuntu .deb sources will also generally remain installed, but as others have noted in the issue, sometimes situations require removing some .deb packages even if they were installed from the default sources (particularly if they involve dependency relationships with low-level system packages, like a desktop environment would).

If you downloaded apps from websites or added third-party PPA sources, those sources will be removed and the leftover apps removed. Those are the ones you'll definitely need to re-install yourself afterward (we would have no way to "automatically re-install the removed packages/apps" since they came from unknown sources and we have no way to know where to go to automatically get the correct version of every possible third-party app for your new OS version).

If you're very concerned about this, just make a list of the apps you have installed before you upgrade so you can reinstall anything you need to afterwards. User data and app configuration files in your home directory will always be retained.
