### ISSUE TITLE
fyletype associations (pop-mimeapps.list) wiped on release upgrade

### ISSUE THREAD

**Issue by Flashwalker** [pop-os/upgrade#309]
Ater release upgrade I found what all of my fyletype associations are wiped  
`~/.local/share/applications/pop-mimeapps.list` is set to default
`~/.local/share/applications/mimeapps.list` is empty

e.g. Asociations/suggestions for .html files are lost

**Comment by mmstick** [comment]
The upgrade daemon does not touch these files.
