### ISSUE TITLE
Failure to upgrade from 20.04 to 22.04

### ISSUE THREAD

**Issue by zacharyrs** [pop-os/upgrade#314]
Hi there,

Hopefully, this is a suitable place to ask for support, if not, just point me in the right direction, please!
I've already posted to the Pop!_OS subreddit [here](https://www.reddit.com/r/pop_os/comments/xjnoir/cant_upgrade_from_2004_to_2204_on_15_machines/), but I'm a bit impatient and hoping I don't have to reinstall the machine.

Essentially. `pop-upgrade` fails, with an issue around `failure to simulate upgrade`.
I've successfully upgraded four similar installs with no issue, though this one had an extra PPA for `jenkins`.
I've already removed that and purged `jenkins`, so I'd assume it's not remanents from there.

I did gather some debug info which I've collated in a [gist](https://gist.github.com/zacharyrs/e7e06776d02b5a55cf4880923feec4ab).

Any advice would be very appreciated, and I can provide any other info requested - I'm trying to avoid a weekend reinstall.

Cheers,
Zach

**Comment by jacobgkau** [comment]
Hello, sorry for the lack of response, GitHub is not the proper place to get support. If you own System76 hardware, you can open a support ticket at [support.system76.com](https://support.system76.com). If not, the subreddit that you linked is available for community support, or we have a fairly active Mattermost chat server at [https://chat.pop-os.org/pop-os/upgrade-help](https://chat.pop-os.org/pop-os/upgrade-help) (that link goes directly to the ~upgrade-help channel.)

Is this still an issue on your system? If you can provide the output of `sudo apt update` to see the current state of the package manager, I would be happy to walk you through repairing/manually upgrading the system. (A refresh install is another way to get past issues like this, but the manual method is not too difficult.)

**Comment by jacobgkau** [comment]
I'm closing this issue due to no response for over a year, assuming you have worked around the issue by now. If you still require assistance, just comment and we can re-open the issue, or visit the Mattermost chat room I linked to before.

We will be testing pop-upgrade extensively for the upcoming 22.04 -> 24.04 upgrade path, but stale issues like this aren't very actionable at this time.
