### ISSUE TITLE
Settings menu item states in OS upgrade and recovery Failed to check for upgrade status. So does Recovery Partition

### ISSUE THREAD

**Issue by Pokey1Kenobi** [pop-os/upgrade#323]
OS upgrade and recovery -> In OS Upgrade it says 'Failed to check for upgrade status  And in OS Recovery it also says 'Failed to check for upgrade status?'  Its said that for at least a few weeks

![image](https://github.com/pop-os/system-updater/assets/26582495/d6b3de45-1f16-428b-979f-d43b44da5006)

**Comment by jacobgkau** [comment]
I'm closing this issue because we haven't heard back from you. If you're still experiencing it, please let me know what `systemctl status pop-upgrade` shows while the issue is occurring.

**Comment by Pokey1Kenobi** [comment]
Hello, thanks for your reply...
pokey1kenobi@pop-os:~$ systemctl status pop-upgrade 
○ pop-upgrade.service
     Loaded: masked (Reason: Unit pop-upgrade.service is masked.)
     Active: inactive (dead)

**Comment by jacobgkau** [comment]
It's not running. Do you have any idea how it got masked?

Run `sudo systemctl unmask pop-upgrade.service` and then `sudo systemctl enable --now pop-upgrade.service` to unmask, enable, and start it again.

**Comment by Pokey1Kenobi** [comment]
Nope, likely related to configuring dns with quad 9 but not sure, its been broken a while the comp went into storage for a bit... running that cmd now...

**Comment by Pokey1Kenobi** [comment]
Created symlink /etc/systemd/system/com.system76.PopUpgrade.service → /lib/systemd/system/pop-upgrade.service.
Created symlink /etc/systemd/system/multi-user.target.wants/pop-upgrade.service → /lib/systemd/system/pop-upgrade.service.
pokey1kenobi@pop-os:~$

**Comment by Pokey1Kenobi** [comment]
The upgrade menu is back!! Thank you so much for making yourself available. Previous attemts on Pop mattermost went unanswered.
Cheers!
is therfe anything else needed to be done? besides updating recovery...

**Comment by jacobgkau** [comment]
>  is therfe anything else needed to be done? besides updating recovery...

No, unless you can use a time machine to go back and figure out why the service got masked and disabled on your machine. That's something that was done either by a user manually, or by a third-party application/script. (Could have been e.g. following a bad tutorial to try and disable automatic updates, for example.)

**Comment by Pokey1Kenobi** [comment]
I have no idea.  I'm curious tho. 
Any suggestions how buy a vowel?

**Comment by Pokey1Kenobi** [comment]
Is there a way to see when automatic updates were disabled?  Sounds like something I would do on android but not my desktop -an xps8700
Or when the last update actually took place?

**Comment by jacobgkau** [comment]
This issue's well over a year old. Your logs have probably been cycled out by now. You can dig around in `sudo journalctl` if you'd like, since it normally logs sudo commands. It will also show any recent automatic updates performed by `pop-system-updater`, if you have them enabled (by default, it only _checks_ for new updates, anyway.)

**Comment by Pokey1Kenobi** [comment]
So, I dug around and found this, are these masked or enabled? : / Should I attempt to re-enable these? 
TIA

pokey1kenobi@pop-os:~$ sudo systemctl list-unit-files | grep masked 
[sudo] password for pokey1kenobi: 
resolvconf-pull-resolved.path                         masked          enabled
acpid.service                                         masked          enabled
alsa-utils.service                                    masked          enabled
cryptdisks-early.service                              masked          enabled
cryptdisks.service                                    masked          enabled
hwclock.service                                       masked          enabled
lvm2.service                                          masked          enabled
rc.service                                            masked          enabled
rcS.service                                           masked          enabled
resolvconf-pull-resolved.service                      masked          enabled
resolvconf.service                                    masked          enabled
saned.service                                         masked          enabled
sudo.service                                          masked          enabled
x11-common.service                                    masked          enabled
pokey1kenobi@pop-os:~$
