### ISSUE TITLE
Upgrading 22.04 to 24.04 during alpha?

### ISSUE THREAD

**Issue by neopostmodern** [pop-os/upgrade#335]
Is it or will it be possible to pass some flag to the upgrader to get a 22.04 machine to the current 24.04 alpha?

**Comment by jacobgkau** [comment]
Yes. We're working on it, but it's not quite ready yet: https://github.com/pop-os/upgrade/pull/330 

Once that PR's been merged/released, the flag to force an upgrade to an unreleased (but programmed) version is `-f`.
