### ISSUE TITLE
Upgrade from 19.04 to 19.10 has minor failure on Nvidia machines with switchable graphics

### ISSUE THREAD

**Issue by isantop** [pop-os/upgrade#39]
After completing an upgrade from 19.04 to 19.10, there is a failure and Pop cannot switch from Intel to Nvidia graphics. 

Upon booting to the upgraded installation, `apt` says there are 7 packages that aren't fully installed or removed. 

![Screenshot from 2019-09-26 14-06-09](https://user-images.githubusercontent.com/5883565/65721451-52fbd580-e067-11e9-935b-7a287f97b76b.png)

These appear to be:

```
nvidia-dkms-435
system76-dkms
system76-io-dkms
nvidia-driver-435
nvidia-driver-418
system76-driver
system76-driver-nvidia
```

**Comment by isantop** [comment]
After fixing the incomplete configurations, the system works correctly and switching works as normal. The system can be switched to Nvidia graphics.

**Comment by mmstick** [comment]
Encountered this on an upgrade from 18.04 to 19.04, and then to 19.10. Noticed that the 5.3 kernel was not installed, and the system kept the 4.18 and 5.0 kernels from 18.04 and 19.04. It would seem that the newer version of dkms in 19.10 cannot build modules for the 5.0 kernel and prior.
