### ISSUE TITLE
During upgrade to 19.10, the Pop_OS NVRAM entry became corrupted

### ISSUE THREAD

**Issue by isantop** [pop-os/upgrade#40]
After upgrading from 19.04 to 19.10, the system (Oryx 4) could not boot Pop_OS and the boot menu did not display it as an option. The only option available was for Windows Boot Manager (there is a Windows installation on this drive, and they use a single EFI System Partition). The output of `efibootmgr -v` is:

```
BootCurrent: 0006
Timeout: 1 seconds
BootOrder: 0005,0006,0007,0002,0000
Boot0000* Pop!_OS 19.04	VenHw(99e275e7-75a0-4b37-a2e6-c5385e6c00cb)
Boot0002* Windows Boot Manager	VenHw(99e275e7-75a0-4b37-a2e6-c5385e6c00cb)WINDOWS.........x...B.C.D.O.B.J.E.C.T.=.{.9.d.e.a.8.6.2.c.-.5.c.d.d.-.4.e.7.0.-.a.c.c.1.-.f.3.2.b.3.4.4.d.4.7.9.5.}...3................
Boot0005* Windows Boot Manager	HD(1,GPT,435e6976-8795-4cae-97a5-e0e5142b8635,0x1000,0xf8fff)/File(\EFI\MICROSOFT\BOOT\BOOTMGFW.EFI)..BO
Boot0006* UEFI OS	HD(1,MBR,0x0,0x0,0x1680)/File(\EFI\BOOT\BOOTX64.EFI)..BO
Boot0007* UEFI OS	HD(2,MBR,0x7fe33249,0x140,0x1680)/File(\EFI\BOOT\BOOTX64.EFI)..BO
```

You can see `Boot0000` exists, but the `VenHw` type entries do not work, and will not allow the system to boot without additional options. They may be Windows-specific.

**Comment by mmstick** [comment]
Was this using the `upgrade` branch of `pop-upgrade`?

**Comment by isantop** [comment]
Yes

**Comment by mmstick** [comment]
Seems `lsblk -no pkname /dev/partition` doesn't work in 19.10

**Comment by mmstick** [comment]
This should be fixed now
