### ISSUE TITLE
19.04 -> 19.10 upgrade fails with "error 100"

### ISSUE THREAD

**Issue by mttkay** [pop-os/upgrade#47]
The instructions from https://support.system76.com/articles/upgrade-pop/ aren't working for me (19.04). The suggested update through the setting GUI fails as shown on the screenshot below. 

![Screenshot from 2019-10-20 09-54-22](https://user-images.githubusercontent.com/102802/67156509-a0462c80-f31f-11e9-920f-2a1ebc613fa7.png)

I then tried to take the terminal route. However, the command from the instructions doesn't exist:

```
$ pop-upgrade release upgrade
/sys/firmware/dmi/tables/smbios_entry_point: Permission denied
/dev/mem: Permission denied
pop-upgrade-release-upgrade 
update the system, and fetch the packages for the next release

USAGE:
    pop-upgrade release upgrade [OPTIONS] <SUBCOMMAND>

OPTIONS:
    -f, --force-next    Attempt to upgrade to the next release, even if it is not released
    -h, --help          Prints help information
    -V, --version       Prints version information

SUBCOMMANDS:
    help        Prints this message or the help of the given subcommand(s)
    recovery    utilize the recovery partition for performing an offline update
    systemd     apply system upgrades offline with systemd's offline-update service
```
I reckon I'm supposed to run this as root instead, but that also doesn't work, it just prints the help, which suggests that this isn't even a valid command?

Someone [on Reddit](https://www.reddit.com/r/pop_os/comments/dk9efp/pop_os_1904_to_1910_upgrade_failed_with_exit_code/f4cvoc3/) suggested that I'd have to install the `pop-desktop` package first. However it's flagged as `conflicts: system76-desktop`, which is just a virtual package. Either way I cannot install it, it fails with another error:

```
$ sudo apt install pop-desktop 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 pop-desktop : Depends: sessioninstaller but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```

Let me know if I can provide any other information that might help to resolve this.

**Comment by mttkay** [comment]
I meanwhile tried both subcommands for `release upgrade [systemd|recovery]`, and both fail with the same message:

```
pop-upgrade: dbus client error: calling ReleaseUpgradeFinalize method failed
```
I captured the entire output here:

```
[1;36mEvent[0m: [1;34mupdating package lists for the current release[0m
[1;36mEvent[0m: [1;34mfetching updated packages for the current release[0m
[1;36mEvent[0m: [1;34mupgrading packages for the current release[0m
[1;36mEvent[0m: [1;34mensuring that system-critical packages are installed[0m
[1;32mRelease upgrade status[0m: [1;31mrelease upgrade aborted[0m: [1;2;31mfailed to install core packages: command failed with exit status: exit code: 100[0m
```
Output is a bit noisy because I think it contains the escape symbols for colored terminal output.

**Comment by mttkay** [comment]
I was able to resolve this by installing `sessioninstaller`:

```
sudo apt install sessioninstaller
```

I don't know why this wasn't installed before, or if it should have.

**Comment by mmstick** [comment]
The most recent merge has improved handling of this error, and a description of what may be wrong.

**Comment by Raizex** [comment]
I am getting this error as well. Sessioninstaller is already installed, and does not resolve the issue.

The issue appears to be that clicking the `download` button on the `settings`->`about` page as per the instructions here: https://support.system76.com/articles/upgrade-pop/ updates `/etc/apt/sources.list` to use ` http://old-releases.ubuntu.com/ubuntu/ disco`. The problem is that Disco is not yet available at http://old-releases.ubuntu.com/ubuntu/, and instead is at http://archive.ubuntu.com/ubuntu/.

This breaks `apt update` and `apt upgrade`, as apt no longer has a valid repo url for the operating systems current version.

**Comment by mmstick** [comment]
@Raizex Yes, exactly. This issue was closed because the fix has already been merged. So you must have attempted the upgrade with the outdated version of the daemon.

**Comment by 1danjordan** [comment]
How do I update the daemon so that I can successfully update? I've followed the [upgrade guide](https://support.system76.com/articles/upgrade-pop/) and [troubleshooting pages](https://support.system76.com/articles/package-manager/) and am still running into this issue of 

```
Release upgrade status: release upgrade aborted: failed to update package lists for the current release: command failed with exit status: exit code: 100
pop-upgrade: dbus client error: calling ReleaseUpgradeFinalize method failed
```

Apologies if this is straightforward, but I can't seem to find a clear solution anywhere.

**Comment by uvinduperera** [comment]
This may cause if you haven't installed `pop-desktop`
Try installing

> `sudo apt install pop-desktop
`
