### ISSUE TITLE
Can't upgrade to new kernel

### ISSUE THREAD

**Issue by Artofaj** [pop-os/upgrade#5]
I installled the newest updates using the popshop. After that problems strated to appear when trying to upgrade packages via terminal. Here the output:

sudo apt-get upgrade
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Calculating upgrade... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
1 not fully installed or removed.
After this operation, 0 B of additional disk space will be used.
Do you want to continue? [Y/n] Y
Setting up linux-image-4.18.0-15-generic (4.18.0-15.16pop2) ...
Processing triggers for linux-image-4.18.0-15-generic (4.18.0-15.16pop2) ...
/etc/kernel/postinst.d/initramfs-tools:
update-initramfs: Generating /boot/initrd.img-4.18.0-15-generic
cryptsetup: WARNING: Resume target cryptswap uses a key file
kernelstub.Config    : INFO     Looking for configuration...
Traceback (most recent call last):
  File "/usr/bin/kernelstub", line 244, in <module>
    main()
  File "/usr/bin/kernelstub", line 241, in main
    kernelstub.main(args)
  File "/usr/lib/python3/dist-packages/kernelstub/application.py", line 141, in main
    config = Config.Config()
  File "/usr/lib/python3/dist-packages/kernelstub/config.py", line 50, in __init__
    self.config = self.load_config()
  File "/usr/lib/python3/dist-packages/kernelstub/config.py", line 60, in load_config
    self.config = json.load(config_file)
  File "/usr/lib/python3.6/json/__init__.py", line 299, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 355, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 17 column 7 (char 287)
run-parts: /etc/initramfs/post-update.d//zz-kernelstub exited with return code 1
run-parts: /etc/kernel/postinst.d/initramfs-tools exited with return code 1
dpkg: error processing package linux-image-4.18.0-15-generic (--configure):
 installed linux-image-4.18.0-15-generic package post-installation script subprocess returned error exit status 1
Errors were encountered while processing:
 linux-image-4.18.0-15-generic
E: Sub-process /usr/bin/dpkg returned an error code (1)

**Comment by Bey0ndB1nary** [comment]
What was the solution to this error? I have the same issue on my Pop OS 20.04 machine.

Thanks.

**Comment by Artofaj** [comment]
The solution was to check the file `/usr/bin/kernelstub`. I had modified mine with some parameters and was causing the problem. Maybe you did the same for adding a splash screen or something like that?
I don't remember exactly what was causing my problem, I think I missed a comma after an argument. Let me know if this solves your problem. Maybe you can post your output .
