### ISSUE TITLE
Systemd upgrade release with CLI

### ISSUE THREAD

**Issue by brs17** [pop-os/upgrade#7]
1. `pop-upgrade release upgrade systemd`
2. Reboot when complete, and wait for upgrade to finish

EDIT: Note `offline` has been replaced with `systemd`

**Comment by brs17** [comment]
- [ ] 18.04
- [ ] 18.10

**Comment by brs17** [comment]
@mmstick I noticed that the boot menu does not get updated with the new release (so an 18.10 install still says 18.04).

**Comment by brs17** [comment]
Looks like an upgrade failed of unencrypted 18.04. After reboot, I get a black screen. Changing virtual terminals I see a blinking cursor but nothing else. When pressing ctrl-alt-del, I get the message: `Failed to remount '/' read-only: Device or resource busy`
![Screenshot from 2019-04-05 18-14-28](https://user-images.githubusercontent.com/7460774/55662371-b7805b00-57cf-11e9-84bc-91f32a88f0b1.png)

logs coming...

**Comment by brs17** [comment]
[installfails.log](https://github.com/pop-os/upgrade/files/3050018/installfails.log)

**Comment by mmstick** [comment]
Seems the upgrade was happening, but failed after getting a SIGINT. Does Plymouth work that system? It should give a plymouth splash which displays text that details the action being performed, and the current progress.

**Comment by brs17** [comment]
On reboot after running `pop-upgrade release upgrade offline`, I do not get any sort of Plymouth screen.

**Comment by mmstick** [comment]
I'll need a solution for systems where Plymouth doesn't work / isn't active.

**Comment by brs17** [comment]
Shouldn't Plymouth be active though?

**Comment by mmstick** [comment]
It should work if the encryption screen also works. Currently looking into how I can improve our Plymouth script with better visuals and text placement for these release upgrades.

**Comment by brs17** [comment]
Just attempted an 18.04 encrypted and 18.04 unencrypted upgrade. Expecting no plymouth screen, on reboot the machines obviously sat there for a while with black screens.

Upon completion I now see two blinking cursors(which makes me assume the upgrade failed). At the blinking cursor I can switch virtual terminals.

**Comment by mmstick** [comment]
When the upgrade fails, it's instructed to reboot and try again, up to a certain number of attempts. If all attempts fail, it resumes with a normal boot.

**Comment by brs17** [comment]
I'll attempt this again and see if I can provide you some logs of what happens

**Comment by brs17** [comment]
I just tried this again and actually got to the decrypt drive screen. The system is now sitting at the `cryptsetup (cryptdata): set up successfully` text. I think when running `pop-upgrade release upgrade offline` or `pop-upgrade recovery upgrade from-release` something makes the decryption process much slower or not work at all.

**Comment by brs17** [comment]
Pressing `f3` I see there is `A start job is running for /dev/mapper/cryptswap (time/no limit)`

**Comment by brs17** [comment]
Pressing `f3` I see there is `A start job is running for /dev/mapper/cryptswap (time/no limit)`

**Comment by brs17** [comment]
The logs should not need to be examined to determine the cause of failure.
We need messaging / a way to handle the error of a ppa that does not have a release for Disco. I think in the case of a PPA, an upgrade should still be possible.

**Comment by brs17** [comment]
> I just tried this again and actually got to the decrypt drive screen. The system is now sitting at the `cryptsetup (cryptdata): set up successfully` text. I think when running `pop-upgrade release upgrade offline` or `pop-upgrade recovery upgrade from-release` something makes the decryption process much slower or not work at all.

^^ May be related to https://github.com/pop-os/pop/issues/503. Will need to re-examine now that that fix has been applied.

**Comment by brs17** [comment]
Just attempted to run this upgrade and unintentionally at the same time `apt` could not get lock` so the installation failed with exit code 100. Having seen the apt lock countless times, I wonder with how this should be dealt.

**Comment by brs17** [comment]
Upgrading a BIOS, Intel machine from 18.04->19.04 (without any ppa issues) worked successfully.

I wonder if we really need `plymouth message --text="system-updates-stop"` when the previous message if I recall correctly was about the system finishing the upgrade and preparing to reboot.

Going to see how it deals with ppa issues next.

**Comment by mmstick** [comment]
I need to add some checks for lock files and proceed only once the system is ready.

**Comment by brs17** [comment]
Just attempted to have `pop-upgrade` remove a ppa that does not exist in disco. After providing a `N` that I did not want to keep it, I was prompted a second time. This is probably the same issue as https://github.com/pop-os/upgrade/issues/16#issuecomment-488350826
